### ISSUE TITLE
New release on RubyGems?

### ISSUE THREAD

**Issue by connorshea** [mbleigh/seed-fu#107]
Rails 5.0.0.rc1 released today, any chance we can get a seed-fu release with the lastest changes to master? :)

Thanks,
Connor

**Comment by connorshea** [comment]
@aserafin Bumping since [Rails 5 has been released today](http://weblog.rubyonrails.org/2016/6/30/Rails-5-0-final/). Any news on a new RubyGems release? :)

Thanks for your work on the gem!

**Comment by aserafin** [comment]
@connorshea just pushed https://rubygems.org/gems/seed-fu/versions/2.3.6 

I don't have any production project currently on Rails 5 so I only checked it with dummy project - please let me know if encounter any issues!

**Comment by connorshea** [comment]
@aserafin thanks!
