### ISSUE TITLE
How to remove entry from Seed

### ISSUE THREAD

**Issue by luckyx1** [mbleigh/seed-fu#110]
If we remove the seed from the fixture file, is there a way to remove the entry without explicitly removing the seed?

**Comment by aserafin** [comment]
Not sure what you're asking exactly, can you elaborate?

**Comment by lime** [comment]
I'm guessing this is the same use case as in #85.

When I use seeds to populate a "static" table, I have the exact list of records in my seeds. 

```ruby
Beverage.seed(:id
  { id: 1, i18n_key: 'coffee' },
  { id: 2, i18n_key: 'tea' }
)
```

Any changes to their attributes are handled nicely by seed-fu, as are additions.

```ruby
Beverage.seed(:id
  { id: 1, i18n_key: 'coffee' },
  { id: 2, i18n_key: 'black tea' },
  { id: 3, i18n_key: 'green tea' }
)
```

But if I want to remove one of the previously seeded records, there doesn't seem to be a way to express it with seed-fu.

Simply removing the record from the seed file won't affect the already seeded database. This is exactly as it should be for most cases. For static tables like these, it would be useful to be able to express that a particular record should no longer be present.

```ruby
Beverage.seed(:id
  { id: 2, i18n_key: 'black tea' },
  { id: 3, i18n_key: 'green tea' }
)

# Coffee is still present in the database
```

I'm guessing the use case is similar for you, @luckyx1?

**Comment by lime** [comment]
I've previously handled this by removing the record in a migration. I use [migration_data] to distinguish data migrations from schema migrations, but using plain ActiveRecord migrations works just as well.

```ruby
class DataRemoveCoffee < ActiveRecord::Migration
  def data
    coffee = Beverage.find_by(id: 1)
    coffee.destroy unless coffee.nil?
  end
end
```

  [migration_data]: https://github.com/ka8725/migration_data

**Comment by luckyx1** [comment]
Yes I ended up doing a migratation_data to remove it, but was wondering if there would be native support to remove it in the future. In any case, thanks everyone, I'll close this 👍
