### ISSUE TITLE
db:seed_fu uses environment from db:test:prepare to seed

### ISSUE THREAD

**Issue by craigmonson** [mbleigh/seed-fu#37]
when I do:
  `%> bundle exec rake db:test:prepare db:seed_fu`

The seed file is written to the _test database.

Now, this seems useful to me actually, so I'm not positive it's an issue at all, however, I've been unable to find any documentation about it.  Is this a feature of seed_fu?  a feature of db:seed?  a feature of rake?

This is the first report, so if it's not an issue with seed_fu, then I'll move on up the stack...
-  rake-0.9.2.2
-  rails-3.1.3
-  seed-fu-2.1.0

**Comment by dgm** [comment]
I haven't looked for sure, but I think db_test_prepare pins the RAILS_ENV to test... and then it probably is still set when seed_fu runs.

**Comment by craigmonson** [comment]
So long ago... doesn't need to be open.
