### ISSUE TITLE
Rails 5 compatibility

### ISSUE THREAD

**Issue by avdmatamoros** [mbleigh/seed-fu#98]
Would it be possible to remove the rails 4 limitation so it'll run with rails 5?

**Comment by connorshea** [comment]
Is this gem no longer maintained?

**Comment by jeremywadsack** [comment]
This was addressed in #99 which was just merged. Maybe this issue can be closed too, @aserafin?

**Comment by aserafin** [comment]
@jeremywadsack you're right, closing

**Comment by connorshea** [comment]
Can this be added to the Changelog then? Thanks for maintaining the gem :)
